"""Give It A Summary - Document Export Tools Module."""

import os
import tempfile
from datetime import datetime
from pathlib import Path

from docx import Document
from docx.enum.style import WD_STYLE_TYPE
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt
from pydantic import BaseModel, Field

from app.utilities.logs import get_logger

logger = get_logger(__name__)


class DocumentExportInputs(BaseModel):
    """Pydantic model for document export inputs."""

    summary: str
    original_filename: str
    word_count: int
    style: str
    output_path: str | None = None


class DocumentExportResult(BaseModel):
    """Result of document export operation."""

    file_path: str = Field(..., description="Path to the generated document")
    file_size: int = Field(..., description="Size of the generated document in bytes")
    success: bool = Field(default=True, description="Whether export was successful")
    error_message: str | None = Field(None, description="Error message if export failed")


def setup_document_styles(doc: Document) -> None:
    """Set up professional document styles."""
    title_style = doc.styles.add_style("CustomTitle", WD_STYLE_TYPE.PARAGRAPH)
    title_style.font.size = Pt(24)
    title_style.font.bold = True
    title_style.font.name = "Arial"
    title_style.paragraph_format.space_after = Pt(24)
    title_style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle_style = doc.styles.add_style("CustomSubtitle", WD_STYLE_TYPE.PARAGRAPH)
    subtitle_style.font.size = Pt(14)
    subtitle_style.font.italic = True
    subtitle_style.font.name = "Arial"
    subtitle_style.paragraph_format.space_after = Pt(18)
    subtitle_style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER

    header_style = doc.styles.add_style("CustomHeader", WD_STYLE_TYPE.PARAGRAPH)
    header_style.font.size = Pt(16)
    header_style.font.bold = True
    header_style.font.name = "Arial"
    header_style.paragraph_format.space_after = Pt(12)

    body_style = doc.styles.add_style("CustomBody", WD_STYLE_TYPE.PARAGRAPH)
    body_style.font.size = Pt(11)
    body_style.font.name = "Times New Roman"
    body_style.paragraph_format.space_after = Pt(8)
    body_style.paragraph_format.line_spacing = 1.15

    meta_style = doc.styles.add_style("CustomMetadata", WD_STYLE_TYPE.PARAGRAPH)
    meta_style.font.size = Pt(10)
    meta_style.font.name = "Arial"
    meta_style.paragraph_format.space_after = Pt(6)


def add_title_page(doc: Document, inputs: DocumentExportInputs) -> None:
    """Add a professional title page to the document."""
    doc.add_paragraph().add_run().add_break()

    title = doc.add_paragraph(style="CustomTitle")
    title.add_run("Academic Document Summary")

    subtitle = doc.add_paragraph(style="CustomSubtitle")
    filename_clean = Path(inputs.original_filename).stem
    subtitle.add_run(f"Summary of: {filename_clean}")

    doc.add_paragraph().add_run().add_break()

    info_para = doc.add_paragraph(style="CustomMetadata")
    info_para.add_run("Generated by Give-It-A-Summary")
    info_para.add_run("\n" + datetime.now().strftime("%B %d, %Y at %I:%M %p"))

    doc.add_page_break()


def add_summary_section(doc: Document, inputs: DocumentExportInputs) -> None:
    """Add the formatted summary section."""
    header = doc.add_paragraph(style="CustomHeader")
    header.add_run("Document Summary")

    summary_para = doc.add_paragraph(style="CustomBody")

    if inputs.style == "bullets":
        lines = inputs.summary.strip().split("\n")
        for line in lines:
            if line.strip():
                summary_para.add_run("• " + line.strip())
                summary_para.add_run("\n")
    else:
        summary_para.add_run(inputs.summary)

    doc.add_paragraph()


def add_metadata_section(doc: Document, inputs: DocumentExportInputs) -> None:
    """Add metadata information at the end."""
    meta_header = doc.add_paragraph(style="CustomHeader")
    meta_header.add_run("Summary Information")

    table = doc.add_table(rows=4, cols=2)
    table.style = "Table Grid"

    table.columns[0].width = Inches(2)
    table.columns[1].width = Inches(4)

    metadata = [
        ("Original Document", inputs.original_filename),
        ("Summary Style", inputs.style.title()),
        ("Word Count", str(inputs.word_count)),
        ("Generation Date", datetime.now().strftime("%Y-%m-%d %H:%M:%S")),
    ]

    for i, (label, value) in enumerate(metadata):
        row = table.rows[i]
        row.cells[0].text = label
        row.cells[1].text = value

        for cell in row.cells:
            for paragraph in cell.paragraphs:
                paragraph.style = "CustomMetadata"


def export_to_word_document(inputs: DocumentExportInputs) -> DocumentExportResult:
    """
    Export summary to a professional Word document.

    Args:
        inputs: Document export parameters

    Returns:
        DocumentExportResult with file path and metadata
    """
    try:
        if inputs.output_path:
            output_path = Path(inputs.output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
        else:
            temp_fd, temp_path = tempfile.mkstemp(suffix=".docx", prefix="summary_")
            os.close(temp_fd)
            output_path = Path(temp_path)

        logger.info("Creating Word document at: %s", output_path)

        doc = Document()

        setup_document_styles(doc)

        add_title_page(doc, inputs)
        add_summary_section(doc, inputs)
        add_metadata_section(doc, inputs)

        doc.save(str(output_path))

        file_size = output_path.stat().st_size

        logger.info("Word document created successfully: %s (%d bytes)", output_path, file_size)

        return DocumentExportResult(file_path=str(output_path), file_size=file_size, success=True)

    except Exception as e:  # noqa: BLE001
        error_msg = f"Document export failed: {str(e)}"
        logger.error("Document export error: %s (%s)", str(e), type(e).__name__)

        if "output_path" in locals() and output_path.exists():
            try:
                output_path.unlink()
            except Exception as cleanup_error:  # noqa: BLE001
                logger.warning(
                    "Failed to cleanup failed export file %s: %s", output_path, str(cleanup_error)
                )

        return DocumentExportResult(
            file_path="", file_size=0, success=False, error_message=error_msg
        )


def cleanup_temp_file(file_path: str) -> bool:
    """
    Clean up a temporary document file.

    Args:
        file_path: Path to the file to clean up

    Returns:
        True if cleanup was successful
    """
    try:
        path = Path(file_path)
        if path.exists() and path.is_file():
            path.unlink()
            logger.info("Cleaned up temporary document file: %s", file_path)
            return True
    except Exception as e:  # noqa: BLE001
        logger.warning("Failed to cleanup temporary file %s: %s", file_path, str(e))

    return False
